name: antinna
# Repository
repository: https://github.com/mg3994/basic_approach_every_app_should_have


packages:
  - core
  - features/*
  - shared/*
command:
  bootstrap:
    environment:
      sdk: ^3.6.0-128.0.dev
      flutter: ">=3.22.0"
    dependencies:
      freezed_annotation: ^2.4.4
      _macros:
        sdk: dart
      

    dev_dependencies:
      flutter_test: 
        sdk: flutter
      bloc_test: ^9.1.7
      build_runner: ^2.4.12
      freezed: ^2.5.7
      json_serializable: ^6.8.0
# Scripts to automate tasks
scripts:
   # Localization code generation for the l10n package
  l10n:
    run: |
      melos exec --scope=l10n "flutter pub run intl_utils:generate"
# Package dependencies

ignore:
  # e.g. ignore example apps
  - '**/example'
  - 'build'