name: dependencies
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0-128.0.dev

# Add regular dependencies here.
dependencies:
  intl: ^0.19.0
  flutter_bloc: ^8.1.6
  macros: ^0.1.2-main.4
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  equatable_macro: ^0.0.1-main.1
  dartz: ^0.10.1
  connectivity_plus: ^6.0.5
  # path: ^1.8.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  lints: ^4.0.0
  test: ^1.24.0
